import './globals.css'
import { Providers } from './components/provider'
import { Navigation } from './components/Navigation'
import { Footer } from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en" className='light'>
      <body>
        <Providers>
          <Navigation />
          <div className='main flex justify-center items-center'>
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
